direction: right
device: Sensor /\nactuator
edge: Edge node\n(inference)
server: Local server
cloud: Cloud / HPC\n(training)

device -> edge: ms
edge -> server: local net
server -> cloud: batch / training
cloud -> edge: updated models
