direction: right
car: A car {
  s1: sensors
  c1: control
  a1: brakes, steering
  s1 -> c1 -> a1
}
factory: A factory {
  s2: sensors
  c2: control
  a2: machines
  s2 -> c2 -> a2
}
building: A building {
  s3: sensors
  c3: control
  a3: HVAC, doors
  s3 -> c3 -> a3
}
