direction: right
l1: Aug 31\nLecture 1
grp: Sep 2\nForm groups
l2: Sep 4\nBuildSim workshop
prop: Sep 11\nProposal
impl: Implement
fin: Oct 12\nFinal submission
oral: Oct 14-19\nOral exam

l1 -> grp -> l2 -> prop -> impl -> fin -> oral
